#ifndef __ARCHI_APB_SOC_H__
#define __ARCHI_APB_SOC_H__

// CONTROL REGISTERS
#define ARCHI_APB_SOC_CONTROL_CLUSTER_OFFSET      0x00
#define ARCHI_APB_SOC_ENABLE_LLC_COUNTERS_OFFSET  0x04
#define ARCHI_APB_SOC_LLC_READ_MISS_CACHE_OFFSET  0x08
#define ARCHI_APB_SOC_LLC_READ_HIT_CACHE_OFFSET   0x0C
#define ARCHI_APB_SOC_LLC_WRITE_MISS_CACHE_OFFSET 0x10
#define ARCHI_APB_SOC_LLC_WRITE_HIT_CACHE_OFFSET  0x14
#define ARCHI_APB_SOC_LLC_CACHE_ADDR_START_OFFSET 0x18
#define ARCHI_APB_SOC_LLC_CACHE_ADDR_END_OFFSET   0x1C
#define ARCHI_APB_SOC_LLC_SPM_ADDR_START_OFFSET   0x20

// CONTROL CLUSTER FIELDS
#define ARCHI_APB_SOC_CONTROL_CLUSTER_RESET_N     0
#define ARCHI_APB_SOC_CONTROL_CLUSTER_EN_SA_BOOT  1
#define ARCHI_APB_SOC_CONTROL_CLUSTER_FETCH_EN    2

#endif


